### ISSUE TITLE
Cleaning up pserv at NERSC

### ISSUE THREAD

**Issue by heather999** [DarkEnergyScienceCollaboration/pserv#14]
My first attempt to read in the Run3 First40 data sadly ended in failure. I believe the problem was due to my running in a directory where I didn't have write access.  I lost the error message, but it was definitely complaining about write permissions.  However, writing to the DB seems to have worked, but it was incomplete since the ingest failed in the middle.
I've since re-run the ingest successfully using another project name:  "Twinkles Run3 First40 Redo" and that looks ok as far as I know.
I'd like to go back and remove the first attempt "Twinkles Run3 First40" - but at heart I'm a chicken.. and maybe it is fine to leave it.  So I'm filing this issue and will confer with @jchiang87 when he returns.

**Comment by drphilmarshall** [comment]
Sounds good, Heather! Will it be easy to rename the tables later? If you
know how to do this, you could rename

"Twinkles Run3 First40" -> "Junk Twinkles Run3 First40"

and then

"Twinkles Run3 First40 Redo" -> ""Twinkles Run3 First40"

With that convention, every table starting with "Junk" could get cleaned
up, later.

**Comment by heather999** [comment]
Yes @drphilmarshall that sounds like a great idea!  I'm just hesitant in that I can see not all the data was written during the first attempt - so I want to make sure that "project" description is used consistently across all the tables.  I think it is supposed to be - but before renaming anything or deleting, I want to be sure we're completely identified all the entries that are associated with "Twinkles Run3 First40".

**Comment by jchiang87** [comment]
Since the "Twinkles Run3 First40" entries are superseded by the "Redo" entries, I don't see any reason not to just delete them and not bother with temporary renaming.  It appears that the only tables with those column values are the `CcdVisit` and `Object` tables and those tables are relatively quick to load for just 40 visits.  I guess we should rename the "Redo" entries, but I'm wondering if that's worth doing if they will soon (I assume) will be superseded by the full Run3 data, at which point I would think we'd just want to delete those "First40 Redo" records.

**Comment by drphilmarshall** [comment]
That would be fine with me, @jchiang87 ! :-)

**Comment by jchiang87** [comment]
The `Twinkles Run3 First40` records have been deleted.
